### ISSUE TITLE
cli doesn't render json object values on response or reply

### ISSUE THREAD

**Issue by jacobythwaites** [opensparkl/sse_cli#10]
To replicate:
```
jthwaites sse1 $ sparkl vars -l data '{"a":3}'
vars
count:	1

	data
	method:	literal
	value:	{"a":3}
jthwaites sse1 $ sparkl tree -a
µ Test
├── ▒ Sequencer:sequencer
├── ƒ data:json
└── >> Solicit:Sequencer data
    └── << Ok data
jthwaites sse1 $ sparkl call Solicit
response
id:	J-YOL-YR9-K02
name:	Ok

	datum
	field:	B-YOL-YR9-JYA
	name:	data
	type:	json

Traceback (most recent call last):
  File "/usr/local/bin/sparkl", line 11, in <module>
    load_entry_point('sparkl-cli==1.3.5', 'console_scripts', 'sparkl')()
  File "/usr/local/lib/python3.6/site-packages/sparkl_cli/main.py", line 275, in main
    show_struct(result)
  File "/usr/local/lib/python3.6/site-packages/sparkl_cli/common.py", line 484, in show_struct
    show_struct(content_object, indent + 1)
  File "/usr/local/lib/python3.6/site-packages/sparkl_cli/common.py", line 484, in show_struct
    show_struct(content_object, indent + 1)
  File "/usr/local/lib/python3.6/site-packages/sparkl_cli/common.py", line 472, in show_struct
    tag = json_object["tag"]
KeyError: 'tag'
jthwaites sse1 $ 
jthwaites sse1 $ sparkl session
session
dir:	/var/folders/b8/hb6pxq_56y3bdl3ywdt5vnqr0000gp/T/sse_cli/39338
id:	39338
jthwaites sse1 $ sparkl call Solicit
response
id:	J-YOL-YR9-K02
name:	Ok

	datum
	field:	B-YOL-YR9-JYA
	name:	data
	type:	json

Traceback (most recent call last):
  File "/usr/local/bin/sparkl", line 11, in <module>
    load_entry_point('sparkl-cli==1.3.5', 'console_scripts', 'sparkl')()
  File "/usr/local/lib/python3.6/site-packages/sparkl_cli/main.py", line 275, in main
    show_struct(result)
  File "/usr/local/lib/python3.6/site-packages/sparkl_cli/common.py", line 484, in show_struct
    show_struct(content_object, indent + 1)
  File "/usr/local/lib/python3.6/site-packages/sparkl_cli/common.py", line 484, in show_struct
    show_struct(content_object, indent + 1)
  File "/usr/local/lib/python3.6/site-packages/sparkl_cli/common.py", line 472, in show_struct
    tag = json_object["tag"]
KeyError: 'tag'
```
The transaction has worked fine. Check the sequencer listen output:
```
$ sparkl -s 39338 listen Sequencer
txn_start
service:	admin@localhost/Scratch/Test/Sequencer

	txn
	node:	sse1@sparkl01.local
	txn_id:	E-YOL-YR9-L36
solicit
service:	admin@localhost/Scratch/Test/Sequencer
solicit:	admin@localhost/Scratch/Test/Solicit

	field
	name:	data
	type:	json
	value:	{
  "a": 3
}
response
response:	admin@localhost/Scratch/Test/Solicit/Ok
service:	admin@localhost/Scratch/Test/Sequencer

	field
	name:	data
	type:	json
	value:	{
  "a": 3
}
txn_end
service:	admin@localhost/Scratch/Test/Sequencer

	txn
	reason:	normal
	txn_id:	E-YOL-YR9-L36

```

**Comment by jacobythwaites** [comment]
A non-object JSON value is fine:
```
$ sparkl vars -l data 3
vars
count:	1

	data
	method:	literal
	value:	3
jthwaites sse1 $ sparkl call Solicit
response
id:	J-YOL-YR9-K02
name:	Ok

	datum
	field:	B-YOL-YR9-JYA
	name:	data
	type:	json
~~~~
3
~~~~
```
